CREATE DATABASE doingsdone
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

USE doingsdone;

CREATE TABLE project (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128),
  user_id INT
);

CREATE TABLE task (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date_create TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  is_done BOOL DEFAULT FALSE,
  name VARCHAR(128),
  file_link VARCHAR(128),
  date_done TIMESTAMP,
  user_id INT,
  project_id INT

);

CREATE TABLE user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  date_reg TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  email VARCHAR(128) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  password VARCHAR(255) NOT NULL
);
